"""add many-to-many assignees to tasks and risks

Revision ID: 5d0bc7948f71
Revises: 5a9a3557b79c
Create Date: 2026-05-12 07:00:07.999561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d0bc7948f71'
down_revision = '5a9a3557b79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assignees',
    sa.Column('risk_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('risk_id', 'user_id')
    )
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('risks_assigned_to_fkey'), type_='foreignkey')
        batch_op.drop_column('assigned_to')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tasks_assigned_to_fkey'), type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tasks_assigned_to_fkey'), 'users', ['assigned_to'], ['id'])

    with op.batch_alter_table('risks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('risks_assigned_to_fkey'), 'users', ['assigned_to'], ['id'])

    op.drop_table('task_assignees')
    op.drop_table('risk_assignees')
    # ### end Alembic commands ###
